# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
    title: Project API
    description: API for EVA Project
    version: "1.0.0"
produces:
    - application/json
consumes:
    - application/json
schemes:
    - http
basePath: /api/api
paths:
    /leerlingen:
        get:
            summary: Leerlingen
            description: Geeft de lijst van alle leerlingen weer
            responses:
                200:
                    title: Leerlingen
                    description: Geeft een lijst van leerlingen
                    scheme:
                        type: array
                        items: 
                            $ref: '#/definitions/Leerling'
        post:
            summary: Leerlingen toevoegen
            description: Voegt een leerling toe
            parameters:
                - name: Leerling
                  in: body
                  description: De JSON van de leerling die je wilt toevoegen
                  schema: 
                      $ref: '#/definitions/Leerling'
            responses:
                201: 
                    description: Leerling succesvol toegevoegd

    /Leerling/{inschrijvingsNr}:
            get:
                summary: Leerling met inschrijvingsNr
                description: Geeft de leerling met het inschrijvingsnr terug
                parameters:
                    - $ref: '#/parameters/inschrijvingsNr'
                responses:
                    200:
                        title: Leerling
                        description: De leerling met het inschrijvingsnr
                        scheme:
                            $ref: '#/definitions/Leerling'
                            
            put:
                summary: Leerlingen aanpassen
                description: Voegt een leerling toe
                parameters:
                    - $ref: '#/parameters/inschrijvingsNr'
                    - name: Leerling
                      in: body
                      description: De JSON van de leerling die je wilt aanpassen
                      schema: 
                          $ref: '#/definitions/Leerling'
                responses:
                    204: 
                        description: Leerling succesvol toegevoegd
                        
            delete:
                summary: Leerling verwijderen
                description: verwijderd de leerling met LeerlingNr
                parameters:
                    - $ref: '#/parameters/inschrijvingsNr'
                responses:
                    204:
                        description: Leerling succesvol verwijderd
                        
    /Leerling/{inschrijvingsNr}/Eva{evaId}:
            get:
                summary: Evaluatiemoment
                description: Geeft de leerling met het inschrijvingsnr terug
                parameters:
                    - $ref: '#/parameters/inschrijvingsNr'
                    - $ref: '#/parameters/evaId'
                    
                responses:
                    200:
                        title: Evaluatie
                        description: De geslecteerde evalutie v/de geselecteerde leerling
                        scheme:
                            $ref: '#/definitions/Eva'
                            
            put:
                summary: Evaluatie aanpassen
                description: Voegt een leerling toe
                parameters:
                    - $ref: '#/parameters/inschrijvingsNr'
                    - $ref: '#/parameters/evaId'
                    - name: Eva
                      in: body
                      description: De JSON van de eva die je wilt aanpassen
                      schema: 
                        $ref: '#/definitions/Eva'
                responses:
                    204: 
                        description: Leerling succesvol toegevoegd
                        
            delete:
                summary: Evaluatiemoment verwijderen
                description: Verwijderd het geselecteerde evaluatiemoment v/d geselecteerde leerling
                parameters:
                    - $ref: '#/parameters/inschrijvingsNr'
                    - $ref: '#/parameters/evaId'
                responses:
                    204:
                        description: Evaluatiemoment v/d leerling is succesvol verwijderd
# -- PARAMETERS -- 
parameters:
    inschrijvingsNr:
        name: inschrijvingsNr
        in: path
        type: string
        description: inschrijvingsnr v/d leerling
        required: true
        
    evaId:
        name: evaId
        description: id van het evaluatiemoment
        in: path
        type: integer
        required: true
        default: 1
        minimum: 1
        maximum: 3

# -- DEFINITIONS --
defintions:
    Leerling:
        type: object
        properties:
            naam:
                type: string
                description: De naam v/d leerling
            inschrijvingsnr:
                type: string
                description: De unieke id van de leerling
                
    Eva:
        type: object
        properties:
            id: 
                type: integer
                description: De unieke id van de evaluatie
            # todo: properties toevoegen
        
          

